/**
 * Card copy.
 *
 * Written from the user's side of the screen: each line says what the control
 * does or what state the route is in, with no filler and no apologising. The
 * rule the card enforces — an empty allowlist means "everything" — is stated
 * in words under the list, because it is the one thing a pin list cannot show
 * on its own.
 *
 * @module @gitawego/dsh-llm-provider/client/strings
 */

/** English copy. */
export const en = {
    routeName: 'OpenCode Go',
    sessionOn: 'Session routing on',
    sessionOff: 'Session routing off',
    models: 'Models',
    read: 'Read',
    reading: 'Reading the provider…',
    readFailed: 'Could not read the provider',
    noModels: 'The provider reported no models',
    noMatch: 'No model matches that filter',
    allAvailable: 'All {n} available',
    pinnedOf: '{pinned} of {served} pinned',
    catalogHint: 'Model list comes from the provider and models.dev',
    filter: 'Filter',
    hideFilter: 'Hide filter',
    filterPlaceholder: 'Filter by id',
    pin: 'Allow',
    unpin: 'Stop allowing',
    retired: 'no longer served',
    allowlistRule: 'Nothing pinned = every model the provider serves is available. Pin one or more to allow only those.',
    useAll: 'Allow every model',
    refresh: 'Refresh',
    configuration: 'Configuration',
    credential: 'Credential reference',
    credentialHint: 'Name this route resolves the key by. The key itself is stored in the credential store, never here.',
    apiKey: 'API key',
    apiKeyHint: 'Stored under the reference above, in the credential store — not in settings.yaml. Leave blank to keep the stored key.',
    apiKeyStored: 'A key is stored for this reference.',
    apiKeyMissing: 'No key is stored for this reference yet.',
    apiKeyUnknown: 'Credential store unreachable.',
    apiKeySave: 'Store key',
    apiKeySaving: 'Storing…',
    apiKeyStoredNow: 'Key stored.',
    pickModels: 'Choose models',
    pickerCount: '{n} of {served} selected',
    pickerHint: 'Selected models are the ones this route may use. Selecting all keeps it following the provider.',
    pickAll: 'Select all',
    pickNone: 'Select none',
    pickApply: 'Use selected',
    cancel: 'Cancel',
    withheld: '{n} more models are available — use Choose models to add them.',
    endpoint: 'Endpoint',
    endpointHint: 'Blank uses each model’s own endpoint from the catalog.',
    sessionRouting: 'Session routing header',
    sessionRoutingHint: 'Required by OpenCode Go; turning it off makes every request fail.',
    reasoning: 'Default thinking effort',
    reasoningHint: 'Applied when a request does not choose one.',
    providerDefault: 'Provider default',
    on: 'On',
    off: 'Off',
    pixels: 'Image pixels per request',
    pixelsHint: 'Total pixel budget across the images of one request.',
    imageBytes: 'Image bytes each',
    imageBytesHint: 'Encoded-byte target for each image before base64.',
    requestBytes: 'Image bytes per request',
    requestBytesHint: 'Oldest images offload first once this is exceeded.',
    allowance: 'Allowance',
    quotaHint: 'Not read yet.',
    quotaCommandHint: 'The same numbers are available to the agent as the llm_quota tool, and in chat as /llm-provider quota.',
    saveFailed: 'Save rejected',
    save: 'Save',
    saving: 'Saving…',
    discard: 'Discard',
} as const

/** Chinese copy, keyed identically. */
export const zh: Record<keyof typeof en, string> = {
    routeName: 'OpenCode Go',
    sessionOn: '会话路由已开启',
    sessionOff: '会话路由已关闭',
    models: '模型',
    read: '读取于',
    reading: '正在读取服务方…',
    readFailed: '无法读取服务方',
    noModels: '服务方未返回任何模型',
    noMatch: '没有匹配该筛选的模型',
    allAvailable: '全部 {n} 个可用',
    pinnedOf: '已固定 {pinned} / {served}',
    catalogHint: '模型列表来自服务方与 models.dev',
    filter: '筛选',
    hideFilter: '隐藏筛选',
    filterPlaceholder: '按 id 筛选',
    pin: '允许',
    unpin: '取消允许',
    retired: '已不再提供',
    allowlistRule: '未固定任何模型 = 服务方提供的全部模型可用。固定一个或多个则仅允许这些。',
    useAll: '允许全部模型',
    refresh: '刷新',
    configuration: '配置',
    credential: '凭据引用',
    credentialHint: '此路由用于解析密钥的名称；密钥本身存于凭据库，不在此处。',
    apiKey: 'API Key',
    apiKeyHint: '将存入上方引用名下的凭据库，而非 settings.yaml。留空表示保留已存密钥。',
    apiKeyStored: '该引用已存有密钥。',
    apiKeyMissing: '该引用尚未存有密钥。',
    apiKeyUnknown: '无法访问凭据库。',
    apiKeySave: '保存密钥',
    apiKeySaving: '保存中…',
    apiKeyStoredNow: '密钥已保存。',
    pickModels: '选择模型',
    pickerCount: '已选 {n} / {served}',
    pickerHint: '所选模型即此路由可用的模型；全选则继续跟随服务方。',
    pickAll: '全选',
    pickNone: '全不选',
    pickApply: '使用所选',
    cancel: '取消',
    withheld: '另有 {n} 个模型可用 — 点击「选择模型」添加。',
    endpoint: '接入地址',
    endpointHint: '留空则使用目录中各模型自身的地址。',
    sessionRouting: '会话路由请求头',
    sessionRoutingHint: 'OpenCode Go 必需；关闭后所有请求都会失败。',
    reasoning: '默认思考强度',
    reasoningHint: '当请求未指定时使用。',
    providerDefault: '服务方默认',
    on: '开启',
    off: '关闭',
    pixels: '每请求图像像素',
    pixelsHint: '一次请求中所有图像的总像素预算。',
    imageBytes: '单张图像字节',
    imageBytesHint: 'base64 编码前每张图像的目标字节数。',
    requestBytes: '每请求图像字节',
    requestBytesHint: '超过后从最旧的图像开始卸载。',
    allowance: '用量额度',
    quotaHint: '尚未读取。',
    quotaCommandHint: '相同数据也可由 llm_quota 工具获取，或在对话中运行 /llm-provider quota。',
    saveFailed: '保存被拒绝',
    save: '保存',
    saving: '保存中…',
    discard: '放弃',
}
