/**
 * Section copy.
 *
 * Written from the user's side of the screen: each label names what the control
 * does, and the notes say what the reader cannot see from the field — that the
 * shipped endpoints are fixed, that the free servers need no key, and where in
 * the chain a backend is tried.
 *
 * @module @gitawego/dsh-web-search/client/strings
 */

/** English copy. */
export const en = {
    nav: 'Web search',
    sectionTitle: 'Web search',
    sectionIntro: 'Backends are tried in the order below; the first one that returns results answers the search.',
    chainTitle: 'Backends, in order',
    limitsTitle: 'Limits',
    builtIn: 'built in',
    free: 'free',
    on: 'On',
    off: 'Off',
    edit: 'Edit',
    hide: 'Hide',
    llmTitle: 'Custom LLM endpoint',
    llmNote: 'Your own endpoint and model, using the provider’s own web-search tool. Tried first when enabled.',
    enabled: 'Enabled',
    protocol: 'Protocol',
    protocolAnthropic: 'Anthropic Messages',
    protocolOpenai: 'OpenAI chat completions',
    baseUrl: 'Endpoint',
    baseUrlHint: 'Base URL of the endpoint, e.g. https://opencode.ai/zen/go/v1.',
    credential: 'Credential reference',
    credentialHint: 'Name of the stored key this endpoint resolves. The key itself lives in the credential store.',
    model: 'Model',
    modelHint: 'Must implement the provider’s web-search tool; the shipped default does.',
    llmTimeout: 'Timeout (ms)',
    goTitle: 'OpenCode Go',
    goNote: 'Shipped endpoint and model. Add a credential reference to use it; it is skipped silently when the key is missing.',
    goCredential: 'Credential reference',
    goCredentialHint: 'Defaults to OPENCODE_GO_API_KEY.',
    token: 'Token (optional)',
    tokenHint: 'Stored in the credential store under the reference above — never in settings.yaml. Leave blank to keep a stored token.',
    storeToken: 'Store token',
    tokenStored: 'A token is stored for this reference.',
    tokenMissing: 'No token is stored for this reference yet.',
    tokenUnknown: 'Credential store unreachable.',
    tokenNeedsReference: 'Name a credential reference above to store a token for it.',
    tokenSaved: 'Token stored.',
    serversTitle: 'Your MCP servers',
    serversNote: 'Called after the shipped servers, in the order listed. Each is called with its tool and its reply read as a Parallel or Exa style result.',
    serversEmpty: 'No servers added. The three backends above are enough for most setups.',
    addServer: 'Add server',
    serverUrl: 'Endpoint',
    serverLabel: 'Label',
    serverTool: 'MCP tool',
    serverToolHint: 'Tool to call; web_search by default.',
    removeServer: 'Remove',
    freeTimeout: 'Free backend timeout (ms)',
    snippetMaxChars: 'Snippet length (chars)',
    maxResults: 'Results per search',
    saveFailed: 'Save rejected — fix the highlighted fields and save again.',
    configured: 'Configured in this deployment.',
    notConfigured: 'Using the shipped defaults.',
    save: 'Save',
    saving: 'Saving…',
    discard: 'Discard',
} as const

/** Chinese copy, keyed identically. */
export const zh: Record<keyof typeof en, string> = {
    nav: '网页搜索',
    sectionTitle: '网页搜索',
    sectionIntro: '后端按下列顺序依次尝试；第一个返回结果的后端即为本次搜索结果。',
    chainTitle: '后端（按顺序）',
    limitsTitle: '限制',
    builtIn: '内置',
    free: '免费',
    on: '开启',
    off: '关闭',
    edit: '编辑',
    hide: '收起',
    llmTitle: '自定义 LLM 端点',
    llmNote: '使用你自己的端点与模型，调用服务方的网页搜索工具。启用后优先尝试。',
    enabled: '启用',
    protocol: '协议',
    protocolAnthropic: 'Anthropic Messages',
    protocolOpenai: 'OpenAI chat completions',
    baseUrl: '接入地址',
    baseUrlHint: '端点的基础地址，例如 https://opencode.ai/zen/go/v1。',
    credential: '凭据引用',
    credentialHint: '此端点解析的密钥名称；密钥本身存于凭据库。',
    model: '模型',
    modelHint: '需实现服务方的网页搜索工具；默认值已满足。',
    llmTimeout: '超时（毫秒）',
    goTitle: 'OpenCode Go',
    goNote: '内置端点与模型。填入凭据引用即可使用；缺少密钥时会静默跳过。',
    goCredential: '凭据引用',
    goCredentialHint: '默认 OPENCODE_GO_API_KEY。',
    token: 'Token（可选）',
    tokenHint: '存入上方引用名下的凭据库，而非 settings.yaml。留空表示保留已存 Token。',
    storeToken: '保存 Token',
    tokenStored: '该引用已存有 Token。',
    tokenMissing: '该引用尚未存有 Token。',
    tokenUnknown: '无法访问凭据库。',
    tokenNeedsReference: '请先在上方填写凭据引用名，再保存 Token。',
    tokenSaved: 'Token 已保存。',
    serversTitle: '自定义 MCP 服务器',
    serversNote: '在内置服务器之后按列出顺序调用。使用各自的工具调用，返回结果按 Parallel 或 Exa 格式解析。',
    serversEmpty: '尚未添加服务器。多数情况下上面三个后端已经足够。',
    addServer: '添加服务器',
    serverUrl: '接入地址',
    serverLabel: '名称',
    serverTool: 'MCP 工具',
    serverToolHint: '要调用的工具；默认 web_search。',
    removeServer: '移除',
    freeTimeout: '免费后端超时（毫秒）',
    snippetMaxChars: '摘要长度（字符）',
    maxResults: '每次搜索结果数',
    saveFailed: '保存被拒绝 —— 请修正高亮字段后重试。',
    configured: '本部署已配置。',
    notConfigured: '使用内置默认值。',
    save: '保存',
    saving: '保存中…',
    discard: '放弃',
}
